# Generated by Django 3.1.7 on 2021-09-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boroughs',
            new_name='Borough',
        ),
    ]
