# Generated by Django 3.1.7 on 2021-09-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210927_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
